# -*- coding: utf-8 -*-
"""
Datos SEMILLA ILUSTRATIVOS del portafolio de empresas estatales (FONAFE y otras).

⚠️  Estas cifras son ILUSTRATIVAS, generadas para poblar la demo mientras el ETL
    no carga los estados financieros oficiales (FONAFE/SMV/MEF). NO usar para análisis real.
    Cada registro publicado se marca con is_illustrative=True.

Unidades: millones de soles (S/ MM), salvo employees (personas).
Años cubiertos: 2019–2024.
"""

YEARS = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
# Nota: cada `trend` define el tramo 2019–2024 (con el efecto pandemia).
# build_dataset.py extrapola hacia atrás (2015–2018) y hacia adelante (2025).
TREND_YEARS = [2019, 2020, 2021, 2022, 2023, 2024]

# trend = multiplicadores por año aplicados al valor base de 2024 (último = 1.0)
# permite series deterministas y reproducibles (sin aleatoriedad -> versionado estable)
COMPANIES = [
    # slug, nombre, sigla, sector, holding, ruc, web, empleados, base2024(rev,net,ebitda,inv,budget), trend_rev, directorio, transp(fin,mem,dir,pres), descripcion
    dict(slug="banco-nacion", name="Banco de la Nación", acronym="BN", sector="Finanzas", holding="FONAFE",
         ruc="20100030595", web="https://www.bn.com.pe", employees=4800,
         rev=3850, net=820, ebitda=1180, inv=240, budget=1100,
         trend=[0.82, 0.79, 0.88, 0.95, 0.98, 1.0],
         directors=[("Presidente del Directorio", "—"), ("Gerente General", "—")],
         transp=(True, True, True, True),
         desc="Banco estatal que opera servicios financieros del Estado y bancariza zonas sin oferta privada."),
    dict(slug="cofide", name="Corporación Financiera de Desarrollo", acronym="COFIDE", sector="Finanzas", holding="FONAFE",
         ruc="20100116392", web="https://www.cofide.com.pe", employees=520,
         rev=620, net=95, ebitda=210, inv=40, budget=180,
         trend=[0.9, 0.85, 0.92, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, False),
         desc="Banco de desarrollo de segundo piso: canaliza financiamiento para infraestructura y mipymes."),
    dict(slug="agrobanco", name="Banco Agropecuario", acronym="Agrobanco", sector="Finanzas", holding="FONAFE",
         ruc="20504565794", web="https://www.agrobanco.com.pe", employees=380,
         rev=180, net=-45, ebitda=-12, inv=15, budget=95,
         trend=[1.4, 1.25, 1.1, 1.05, 1.02, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, False, True, False),
         desc="Banca de fomento agropecuario; arrastra pérdidas y reestructuración tras crisis de cartera."),
    dict(slug="fondo-mivivienda", name="Fondo MIVIVIENDA", acronym="FMV", sector="Finanzas", holding="FONAFE",
         ruc="20511904162", web="https://www.mivivienda.com.pe", employees=470,
         rev=540, net=160, ebitda=240, inv=30, budget=210,
         trend=[0.86, 0.9, 0.94, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, True),
         desc="Promueve el acceso a vivienda mediante créditos y bonos habitacionales."),
    dict(slug="electroperu", name="Electroperú", acronym="ELP", sector="Energía", holding="FONAFE",
         ruc="20100128218", web="https://www.electroperu.com.pe", employees=620,
         rev=1980, net=410, ebitda=720, inv=320, budget=560,
         trend=[0.88, 0.8, 0.92, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, True),
         desc="Mayor generadora eléctrica estatal (Mantaro). Pilar del sistema interconectado."),
    dict(slug="egasa", name="Empresa de Generación Eléctrica de Arequipa", acronym="EGASA", sector="Energía", holding="FONAFE",
         ruc="20211113477", web="https://www.egasa.com.pe", employees=210,
         rev=420, net=78, ebitda=150, inv=70, budget=120,
         trend=[0.9, 0.86, 0.93, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, False),
         desc="Generación hidro y térmica en el sur. Clave para Arequipa y el sur peruano."),
    dict(slug="egemsa", name="Empresa de Generación Eléctrica Machupicchu", acronym="EGEMSA", sector="Energía", holding="FONAFE",
         ruc="20114915035", web="https://www.egemsa.com.pe", employees=180,
         rev=300, net=62, ebitda=120, inv=55, budget=90,
         trend=[0.91, 0.87, 0.94, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, False, False),
         desc="Central Machupicchu; abastece el sur oriente y la demanda turística de Cusco."),
    dict(slug="egesur", name="Empresa de Generación Eléctrica del Sur", acronym="EGESUR", sector="Energía", holding="FONAFE",
         ruc="20203250619", web="https://www.egesur.com.pe", employees=95,
         rev=110, net=8, ebitda=28, inv=18, budget=42,
         trend=[0.94, 0.9, 0.95, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, False, False, False),
         desc="Pequeña generadora del extremo sur (Tacna/Moquegua)."),
    dict(slug="hidrandina", name="Empresa Regional de Servicio Público de Electricidad", acronym="Hidrandina", sector="Energía", holding="FONAFE",
         ruc="20132023540", web="https://www.distriluz.com.pe", employees=1350,
         rev=1450, net=130, ebitda=340, inv=210, budget=400,
         trend=[0.85, 0.82, 0.9, 0.96, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, False),
         desc="Distribución eléctrica en el norte (grupo Distriluz)."),
    dict(slug="corpac", name="Corporación Peruana de Aeropuertos y Aviación Comercial", acronym="CORPAC", sector="Transporte", holding="FONAFE",
         ruc="20100072751", web="https://www.corpac.gob.pe", employees=2100,
         rev=720, net=-38, ebitda=95, inv=180, budget=350,
         trend=[1.3, 1.55, 1.2, 1.05, 1.0, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, False, True, False),
         desc="Servicios de navegación aérea y aeropuertos no concesionados. Golpeada por la pandemia."),
    dict(slug="enapu", name="Empresa Nacional de Puertos", acronym="ENAPU", sector="Transporte", holding="FONAFE",
         ruc="20100022626", web="https://www.enapu.com.pe", employees=1450,
         rev=410, net=44, ebitda=110, inv=85, budget=240,
         trend=[0.92, 0.88, 0.95, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, False, False),
         desc="Administra puertos no concesionados; rol logístico y de cabotaje."),
    dict(slug="serpost", name="Servicios Postales del Perú", acronym="SERPOST", sector="Transporte", holding="FONAFE",
         ruc="20266352337", web="https://www.serpost.com.pe", employees=1600,
         rev=190, net=-22, ebitda=-4, inv=12, budget=120,
         trend=[1.15, 1.1, 1.05, 1.02, 1.0, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, False, False, False),
         desc="Operador postal del Estado; reto de sostenibilidad frente a la digitalización."),
    dict(slug="sedapal", name="Servicio de Agua Potable y Alcantarillado de Lima", acronym="SEDAPAL", sector="Saneamiento", holding="FONAFE",
         ruc="20100152356", web="https://www.sedapal.com.pe", employees=4300,
         rev=3650, net=120, ebitda=980, inv=1450, budget=2100,
         trend=[0.9, 0.86, 0.92, 0.96, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, True, True),
         desc="Mayor empresa de saneamiento del país; abastece agua y alcantarillado a Lima y Callao."),
    dict(slug="sima", name="Servicios Industriales de la Marina", acronym="SIMA", sector="Industrial/Defensa", holding="FONAFE",
         ruc="20154308439", web="https://www.sima.com.pe", employees=2800,
         rev=680, net=35, ebitda=120, inv=90, budget=300,
         trend=[0.88, 0.85, 0.93, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(True, True, False, False),
         desc="Astilleros e industria naval/metalmecánica del Estado."),
    dict(slug="fame", name="Fábrica de Armas y Municiones del Ejército", acronym="FAME", sector="Industrial/Defensa", holding="FONAFE",
         ruc="20517182673", web="https://www.fame.com.pe", employees=520,
         rev=120, net=-9, ebitda=10, inv=22, budget=80,
         trend=[1.05, 1.02, 1.0, 1.0, 1.0, 1.0],
         directors=[("Presidente del Directorio", "—")],
         transp=(False, False, False, False),
         desc="Industria de defensa; producción de armamento y municiones para FF.AA."),

    # --- Distribución eléctrica (grupo Distriluz y regionales) ---
    dict(slug="electrocentro", name="Electrocentro", acronym="Electrocentro", sector="Energía", holding="FONAFE",
         ruc="20133360021", web="https://www.distriluz.com.pe", employees=1100,
         rev=1180, net=92, ebitda=270, inv=160, budget=330,
         trend=[0.86, 0.83, 0.91, 0.96, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, False, False),
         desc="Distribución eléctrica en la región central (Distriluz)."),
    dict(slug="enosa", name="Electronoroeste", acronym="ENOSA", sector="Energía", holding="FONAFE",
         ruc="20162256603", web="https://www.distriluz.com.pe", employees=820,
         rev=960, net=70, ebitda=210, inv=120, budget=260,
         trend=[0.87, 0.84, 0.92, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, False, False),
         desc="Distribución eléctrica en el noroeste (Piura/Tumbes)."),
    dict(slug="ensa", name="Electronorte", acronym="ENSA", sector="Energía", holding="FONAFE",
         ruc="20395456042", web="https://www.distriluz.com.pe", employees=780,
         rev=900, net=66, ebitda=200, inv=110, budget=240,
         trend=[0.87, 0.84, 0.92, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, False),
         desc="Distribución eléctrica en Lambayeque y zona norte."),
    dict(slug="electro-oriente", name="Electro Oriente", acronym="ELOR", sector="Energía", holding="FONAFE",
         ruc="20103464001", web="https://www.elor.com.pe", employees=1050,
         rev=1020, net=58, ebitda=220, inv=180, budget=300,
         trend=[0.85, 0.82, 0.9, 0.96, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, True),
         desc="Distribución y generación en la Amazonía (Loreto, San Martín, Amazonas)."),
    dict(slug="electro-sur-este", name="Electro Sur Este", acronym="ELSE", sector="Energía", holding="FONAFE",
         ruc="20116544289", web="https://www.else.com.pe", employees=900,
         rev=940, net=72, ebitda=205, inv=140, budget=270,
         trend=[0.86, 0.83, 0.91, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, False),
         desc="Distribución eléctrica en Cusco, Apurímac y Madre de Dios."),
    dict(slug="electro-puno", name="Electro Puno", acronym="ELPU", sector="Energía", holding="FONAFE",
         ruc="20115667917", web="https://www.electropuno.com.pe", employees=520,
         rev=480, net=24, ebitda=92, inv=70, budget=150,
         trend=[0.88, 0.85, 0.93, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, False, False, False),
         desc="Distribución eléctrica en la región Puno."),
    dict(slug="electro-ucayali", name="Electro Ucayali", acronym="ELUC", sector="Energía", holding="FONAFE",
         ruc="20393485416", web="https://www.electroucayali.com.pe", employees=320,
         rev=300, net=14, ebitda=58, inv=42, budget=95,
         trend=[0.89, 0.86, 0.93, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, False, False, False),
         desc="Distribución eléctrica en Ucayali."),
    dict(slug="seal", name="Sociedad Eléctrica del Sur Oeste", acronym="SEAL", sector="Energía", holding="FONAFE",
         ruc="20100188763", web="https://www.seal.com.pe", employees=980,
         rev=1280, net=104, ebitda=300, inv=190, budget=360,
         trend=[0.86, 0.83, 0.91, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, True),
         desc="Distribución eléctrica en Arequipa."),
    dict(slug="adinelsa", name="Empresa de Administración de Infraestructura Eléctrica", acronym="ADINELSA", sector="Energía", holding="FONAFE",
         ruc="20259752803", web="https://www.adinelsa.com.pe", employees=180,
         rev=160, net=18, ebitda=42, inv=60, budget=110,
         trend=[0.9, 0.88, 0.94, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, False, False),
         desc="Administra infraestructura eléctrica rural transferida por el Estado."),

    # --- Hidrocarburos ---
    dict(slug="petroperu", name="Petróleos del Perú", acronym="PETROPERÚ", sector="Hidrocarburos", holding="Estado (MINEM/FONAFE)",
         ruc="20100128218", web="https://www.petroperu.com.pe", employees=2600,
         rev=24800, net=-3200, ebitda=-450, inv=1200, budget=3800,
         trend=[0.78, 0.7, 0.95, 1.05, 1.02, 1.0],
         directors=[("Presidente del Directorio", "—"), ("Gerente General", "—")], transp=(True, True, True, False),
         desc="Mayor empresa del Estado; refinación y comercialización de combustibles. Refinería de Talara. Crisis financiera y de liquidez."),

    # --- Otras empresas del Estado ---
    dict(slug="editora-peru", name="Editora Perú (El Peruano)", acronym="Editora Perú", sector="Servicios", holding="FONAFE",
         ruc="20100151069", web="https://www.editoraperu.com.pe", employees=620,
         rev=260, net=22, ebitda=48, inv=18, budget=120,
         trend=[0.9, 0.87, 0.94, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, True),
         desc="Editora del diario oficial El Peruano y servicios editoriales del Estado."),
    dict(slug="amsac", name="Activos Mineros", acronym="AMSAC", sector="Minería/Ambiental", holding="FONAFE",
         ruc="20380275754", web="https://www.amsac.pe", employees=210,
         rev=180, net=12, ebitda=40, inv=120, budget=210,
         trend=[0.9, 0.88, 0.94, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, True, False),
         desc="Remediación de pasivos ambientales mineros y gestión de activos del Estado."),
    dict(slug="enaco", name="Empresa Nacional de la Coca", acronym="ENACO", sector="Servicios", holding="FONAFE",
         ruc="20100039207", web="https://www.enaco.com.pe", employees=420,
         rev=140, net=6, ebitda=18, inv=10, budget=70,
         trend=[0.92, 0.9, 0.95, 0.98, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, False, False, False),
         desc="Comercialización legal de la hoja de coca y derivados."),
    dict(slug="silsa", name="Servicios Integrados de Limpieza", acronym="SILSA", sector="Servicios", holding="FONAFE",
         ruc="20259618705", web="https://www.silsa.com.pe", employees=3800,
         rev=210, net=4, ebitda=14, inv=6, budget=90,
         trend=[0.93, 0.91, 0.96, 0.99, 1.0, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, False, False, False),
         desc="Servicios de limpieza y mantenimiento para entidades públicas."),
    dict(slug="esvicsac", name="Empresa de Servicios de Vigilancia Ciudadana", acronym="ESVICSAC", sector="Servicios", holding="FONAFE",
         ruc="20510795618", web="https://www.esvicsac.com.pe", employees=2900,
         rev=190, net=3, ebitda=11, inv=5, budget=80,
         trend=[0.93, 0.91, 0.96, 0.99, 1.0, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(False, False, False, False),
         desc="Servicios de vigilancia y seguridad para el sector público."),

    # --- Más empresas del portafolio ---
    dict(slug="banmat", name="Banco de Materiales (en liquidación)", acronym="BANMAT", sector="Finanzas", holding="FONAFE",
         ruc="20101024645", web="https://www.gob.pe/", employees=80,
         rev=20, net=-18, ebitda=-15, inv=2, budget=30,
         trend=[1.8, 1.6, 1.4, 1.2, 1.05, 1.0],
         directors=[("Liquidador", "—")], transp=(False, False, False, False),
         desc="Entidad en proceso de liquidación; arrastra cartera incobrable de créditos de vivienda."),
    dict(slug="san-gabriel", name="Empresa de Generación Eléctrica San Gabriel", acronym="San Gabriel", sector="Energía", holding="FONAFE",
         ruc="20603000001", web="https://www.electroperu.com.pe", employees=60,
         rev=40, net=-5, ebitda=8, inv=520, budget=600,
         trend=[0.2, 0.4, 0.7, 0.9, 0.97, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, False, False, False),
         desc="Proyecto hidroeléctrico en construcción (afluente del Mantaro); alta inversión, aún sin operación plena."),
    dict(slug="electrosur", name="Electrosur", acronym="Electrosur", sector="Energía", holding="FONAFE",
         ruc="20131367008", web="https://www.electrosur.com.pe", employees=360,
         rev=420, net=30, ebitda=92, inv=60, budget=140,
         trend=[0.88, 0.85, 0.92, 0.97, 0.99, 1.0],
         directors=[("Presidente del Directorio", "—")], transp=(True, True, False, False),
         desc="Distribución eléctrica en Tacna y Moquegua."),
]

# --- Empresas estatales REGIONALES: EPS de saneamiento (una por región) ---
# Municipales (no FONAFE), reguladas por SUNASS. Datos ILUSTRATIVOS; RUC vacío -> match OCDS por nombre.
# (slug, nombre, sigla, region, empleados, ingresos2024_MM)
_EPS = [
    ("sedapar", "Servicio de Agua Potable y Alcantarillado de Arequipa", "SEDAPAR", "Arequipa", 1100, 520),
    ("sedalib", "Servicio de Agua Potable y Alcantarillado de La Libertad", "SEDALIB", "La Libertad", 900, 410),
    ("epsel", "Entidad Prestadora de Servicios de Saneamiento de Lambayeque", "EPSEL", "Lambayeque", 780, 360),
    ("eps-grau", "EPS Grau", "EPS Grau", "Piura", 1050, 470),
    ("sedacusco", "Empresa Prestadora de Servicios de Saneamiento del Cusco", "SEDACUSCO", "Cusco", 520, 240),
    ("sedacaj", "Servicio de Agua Potable y Alcantarillado de Cajamarca", "SEDACAJ", "Cajamarca", 320, 130),
    ("epsasa", "Entidad Prestadora de Servicios de Saneamiento Ayacucho", "EPSASA", "Ayacucho", 280, 95),
    ("emapica", "Empresa Municipal de Agua Potable y Alcantarillado de Ica", "EMAPICA", "Ica", 360, 150),
    ("sedam-huancayo", "Servicio de Agua Potable y Alcantarillado Municipal de Huancayo", "SEDAM Huancayo", "Junín", 480, 200),
    ("eps-tacna", "Empresa Prestadora de Servicios Tacna", "EPS Tacna", "Tacna", 360, 160),
    ("seda-huanuco", "Empresa de Servicio de Agua Potable y Alcantarillado de Huánuco", "SEDA Huánuco", "Huánuco", 300, 110),
    ("emapa-sanmartin", "Empresa Municipal de Agua Potable y Alcantarillado San Martín", "EMAPA San Martín", "San Martín", 340, 130),
    ("emsapuno", "Empresa Municipal de Saneamiento Básico de Puno", "EMSAPUNO", "Puno", 260, 90),
    ("eps-loreto", "Empresa Prestadora de Servicios de Saneamiento de Loreto", "EPS Loreto", "Loreto", 380, 140),
    ("emapacop", "Empresa Municipal de Agua Potable y Alcantarillado de Coronel Portillo", "EMAPACOP", "Ucayali", 240, 80),
    ("emapat", "Empresa Municipal de Agua Potable y Alcantarillado de Tambopata", "EMAPAT", "Madre de Dios", 160, 55),
    ("eps-moquegua", "Empresa Prestadora de Servicios de Saneamiento Moquegua", "EPS Moquegua", "Moquegua", 180, 70),
    ("emusap-amazonas", "Empresa Municipal de Servicios de Agua Potable Amazonas", "EMUSAP Amazonas", "Amazonas", 140, 48),
]
for _slug, _name, _acr, _region, _emp, _rev in _EPS:
    COMPANIES.append(dict(
        slug=_slug, name=_name, acronym=_acr, sector="Saneamiento", holding="EPS Municipal",
        ruc="", web="https://www.sunass.gob.pe/", employees=_emp, region=_region,
        rev=_rev, net=round(_rev * 0.03, 1), ebitda=round(_rev * 0.18, 1),
        inv=round(_rev * 0.22, 1), budget=round(_rev * 0.6, 1),
        trend=[0.9, 0.87, 0.93, 0.97, 0.99, 1.0],
        directors=[("Gerente General", "—")], transp=(True, False, False, False),
        desc=f"Empresa prestadora de servicios de saneamiento (EPS) de la región {_region}. Regulada por SUNASS."))

NEWS_TEMPLATES = [
    ("Convenio de Gestión {y} con FONAFE", "https://www.fonafe.gob.pe/"),
    ("Memoria anual {y} publicada", "https://www.fonafe.gob.pe/"),
    ("Sesión de directorio — acuerdos {y}", "https://www.gob.pe/"),
]
